### ISSUE TITLE
simulated_examples.py gives "predicted y failed, predicted f"

### ISSUE THREAD

**Issue by jakeyeung** [ManchesterBioinference/GP_Transcription_Dynamics#3]
Hi GP team,

Thanks so much for helping me out.

I managed to get the `simulated_examples.py` running but when trying to run `trcd.model.predict_y()` it is giving an error `NameError: name 'F' is not defined`. 

In the simulation code, this happens when trying to run `plot_trcd_predict()`.

The function still runs but gives `predicted y failed, predicted f` 

Any reason why it is unable to `predict_y()` in the simulation? 

Kindest regards,

Jake

**Comment by YuliyaShapovalova** [comment]
Hi Jake, 

Currently, `plot_trcd_predict()` uses only the `trcd.predict_f()` function. The uncertainty due to the measurement noise is added in the `plot_trcd_predict()` function through the terms with the parameters `var_m_noise` and `var_p_noise`. 

`predicted y failed, predicted f` is just a warning, mostly for internal use. We probably will incorporate a more elegant solution in the future. But for now, if you are interested in predictions of y (i.e., with uncertainty due to both f and the measurement noise), the function already works as intended. If you are interested in the prediction of only f, you can remove the terms with `var_m_noise` and `var_p_noise` in them from the `plot_trcd_predict()` function.
